# GROW PARTITION
# Alpine

- name: Ensure that prerequisites are installed.
  apk:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nettle@edge     # A low-level cryptographic library (prereq for cloud-utils)
    - gnutls@edge     # A TLS protocol implementation (prereq for cloud-utils)
    - cloud-utils@testing # Useful set of utilities for interacting with a cloud (growpart)
    - e2fsprogs-extra     # Ext2/3/4 filesystem extra utilities (resize2fs)

- name: Copy script to automatically Grow Partition after resize by Proxmox.
  copy:
    src: auto_grow_partition-alpine.start
    dest: /etc/local.d/05_auto_grow_partition.start
    mode: a+x
  notify: Activate Autostart
