---
# handlers file for ansible-initial-server

# Alpine
# Ensure that local auto-start service is enabled
# - used to start ssh-host-keygen.sh on first boot and the auto-growpart script
- name: Activate Autostart
  service:
    name: local
    runlevel: default
    enabled: yes
  become: true
  become_method: "{{ iserver_become }}"
  tags:
    - vanilla

# Alpine, OpenBSD
- name: Restart SSHD
  service:
    name: sshd
    state: restarted
  become: true
  become_method: "{{ iserver_become }}"
  tags:
    - vanilla